### ISSUE TITLE
Stange syntax highlighting behaviour when working with the same buffer on two splits

### ISSUE THREAD

**Issue by Yodzorah** [ingolemo/vis-smart-backspace#2] opened 2020-08-10 14:24 UTC
# Reproduce

1. Open a file for which you have a lexer, use colored theme.
2. Open a split with the same file.
3. Enter `INSERT` mode in any of the windows, it doesn't matter.
4. Start erasing symbols from the left by one (`<Backspace>`).

# Result

With each erased symbol the coloring in the other window also shifts one symbol to the left, even when you only erase symbols _inside_ of a variable name, like this:

```lua
local long|long|var = 42
```

The deleted symbols are inside of `|`. The coloring inside of the current window stays fine.

# Expected result

No change to syntax highlighting unless it changes on its own when the code structure gets broken by the deletes.

# Doesn't happen for

- different files
- different layouts
- erasing of symbols from the right by one (`<Delete>`)
- other modes

**Comment by ingolemo** [comment] 2020-08-10 15:07
I've pushed a commit with a workaround. I'd appreciate if you could test it. I think this is ultimately a problem that needs to be fixed in vis directly though.

**Comment by Yodzorah** [comment] 2020-08-10 17:29
@ingolemo, yes, it's OK now, but sometime after posting the issue I've encountered this bug even with this plugin turned off. Can't reproduce, though, since what seemed to cause it wasn't causing it before. I'll try to catch it and post an issue to `vis`, but I'm not sure I can. If you found this bug and you know for a fact that your plugin only triggered it, but the bug itself exists in `vis`, and if you can reproduce it without this plugin, maybe you could post the issue to `vis`? Thanks.

**Comment by ingolemo** [comment] 2020-08-10 18:40
The problem is that there's no official way, that I can find, for a plugin to redraw the whole screen. Plugins can redraw the current window with `vis.win:draw()` but this won't update any other splits of the same file. The lua api docs list a `vis:draw()` function which seems promising, but it doesn't actually exist when I try to call it. The vis C source code suggests that this function is actually called `vis:redraw()` which does exist, in spite of the documentation. However, when I call it, it doesn't redraw the screen.

The work-around I'm using right now is to call `vis:insert('')` which does nothing, but has the side-effect of redrawing the screen.

I believe this issue can be triggered by any code that tries to alter the document directly using the File class from the lua api (`File:insert` and `File:delete`), so it's possible that other plugins have the same issue. It should be enough to put this code into your visrc, open a coloured file, run `:split`, and press `a`:

    vis.events.subscribe(vis.events.INIT, function()
        vis:map(vis.modes.NORMAL, 'a', function()
            vis.win.file:insert(vis.win.selection.pos, 'a')
            vis.win:draw()
        end)
    end)

**Closed by ingolemo** 2020-08-10 18:40 UTC

**Comment by Yodzorah** [comment] 2020-08-10 18:49
> The work-around I'm using right now is to call vis:insert('') which does nothing, but has the side-effect of redrawing the screen.

This works for me:

```lua
for win in vis:windows() do
	win:draw()
end
```
